# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7806685896c90089de62daec6ab52839f94370531b61d90d854b58de6b9cb55818d8db3b63473ebd5d9631f0066812fa8e0bd30c0311505e0a13fb40cd92b67d

test:
  secret_key_base: aace26b04371375ee5910a15e992ecac65035a782fb50a839569f88a39c832ad6e1515be72f07922e8da389e6f5333260ba75cdc5c51c4b9207100fbe68f0ca3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
